<section class="photos-grid-container">
    <h1 class="large-title">Album : <?= htmlspecialchars($album->getTitle()) ?></h1>

    <div class="photos-grid">
        <?php foreach ($photos as $photo): ?>
        <div class="photo-item">
            <a href="<?= BASE_URL ?>/photos/show?id=<?= $photo->getId() ?>">
                <img src="/uploads/albums/<?= htmlspecialchars($photo->getFilename()) ?>" alt="file">
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</section>